### ISSUE TITLE
gRPC接口服务端存在bug？

### ISSUE THREAD

**Issue by kingnop** [autodeployai/ai-serving#7]
您好，很高兴你们能够开源改ONNX模型部署框架。但在使用中发现gRPC接口存在bug，我在用如下代码请求grpc接口时并未获得预期结果。
```
with grpc.insecure_channel(self.full_url) as channel:
            stub = ai_serving_pb2_grpc.DeploymentServiceStub(channel)
            response = stub.GetModelMetadata(ai_serving_pb2.ModelSpec(name=self.model_name))

```
预期应该获取到名为model_name的模型的Metadata信息，但获取到的是所有模型的Metadata信息。

**Comment by aipredict** [comment]
@kingnop 我这边无法重现这个问题，如果只是指定模型名称，是获取这个名称下的所有版本的metadata信息，但是不会获取其他名称的模型信息，比如在这个unit test下(https://github.com/autodeployai/ai-serving/blob/master/src/test/scala/ai/autodeploy/serving/PmmlGrpcSpec.scala#L127)，添加了如下测试代码：

```
      blockingStub.deploy(DeployRequest("a-pmml-model", ByteString.copyFrom(Files.readAllBytes(input))))
      val metadataResponseTest = blockingStub.getModelMetadata(GetModelMetadataRequest(Some(ModelSpec("a-pmml-model"))))
      metadataResponseTest.metadata should have size 1
      metadataResponseTest.metadata.head.versions should have size 2
```
 测试是没有问题的，只是指定名称`a-pmml-model`，metadata的大小是1，没有返回`b-pmml-model`的信息，但是`a-pmml-model`有2个版本，所以versions的长度是2

**Comment by aipredict** [comment]
@kingnop 能提供一下您这边的详细操作步骤吗？我们需要能复现这个问题，谢谢

**Comment by kingnop** [comment]
@aipredict 
您好，复现详细操作步骤如下：

### 环境

使用的是Docker环境，从Docker Hub拉取镜像。

```bash
docker pull autodeployai/ai-serving:0.9.4-cuda	
```

然后运行docker容器：

```
docker run --gpus all -it -v /home/autoai:/opt/ai-serving -p 9090:9090 -p 9091:9091 autodeployai/ai-serving:0.9.4-cuda
```

从ONNX Model Zoo下载mnist手写识别模型和resnet图像分类模型，下载地址如下：

> https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.onnx

> https://github.com/onnx/models/blob/master/vision/classification/mnist/model/mnist-1.onnx

### 复现操作步骤

1. 使用http请求方式上传两个模型，分别命名为mnist和resnet50，得到正确的返回（200 OK）

2. 使用gRPC方式调用GetModelMetadata函数获取模型的Metadata。相关代码如下：

   ```python
   class AIServingWithGrpc(object):
       def __init__(self, url, port, model_name):
           self.model_name = model_name
           self.full_url = url + ":" + port
           
       def _get_model_metadata(self):
           with grpc.insecure_channel(self.full_url) as channel:
               stub = ai_serving_pb2_grpc.DeploymentServiceStub(channel)
               response = stub.GetModelMetadata(self._model_spec())
           return response.metadata
   
       def _model_spec(self):
           model_spec = ai_serving_pb2.ModelSpec(name=self.model_name)
           return model_spec
   ```

   下面的代码为请求获取mnist模型的元信息：

   ```python
   if __name__ == '__main__':
       test = AIServingWithGrpc(url="your ip", port="your port", model_name="mnist")
       print(test._get_model_metadata())
   ```

   返回结果为：

   ```json
   [id: "e48a3f92-3f37-4da6-9594-e1743e44184c"
   name: "mnist"
   created_at {
     seconds: 1627365237000
   }
   update_at {
     seconds: 1627365237000
   }
   latest_version: 1
   versions {
     type: "ONNX"
     serialization: "onnx"
     runtime: "ONNX Runtime"
     predictors {
       name: "Input3"
       type: "tensor(float)"
       shape: 1
       shape: 1
       shape: 28
       shape: 28
     }
     outputs {
       name: "Plus214_Output_0"
       type: "tensor(float)"
       shape: 1
       shape: 10
     }
     version {
       value: 1
     }
     hash: "d7cd24a0a76cd492f31065301d468c3d"
     size: 26454
     created_at {
       seconds: 1627365237000
     }
   }
   , id: "9ebaa780-d133-453e-9c96-91ed303e7460"
   name: "resnet50"
   created_at {
     seconds: 1627365264000
   }
   update_at {
     seconds: 1627365264000
   }
   latest_version: 1
   versions {
     type: "ONNX"
     serialization: "onnx"
     runtime: "ONNX Runtime"
     predictors {
       name: "data"
       type: "tensor(float)"
       shape: 1
       shape: 3
       shape: 224
       shape: 224
     }
     outputs {
       name: "resnetv24_dense0_fwd"
       type: "tensor(float)"
       shape: 1
       shape: 1000
     }
     version {
       value: 1
     }
     hash: "22ed6e6a8fb9192f0980acca0c941414"
     size: 102442450
     created_at {
       seconds: 1627365264000
     }
   }
   ]
   
   Process finished with exit code 0
   
   ```

   可以看到返回了2个模型的元信息而不仅是mnist的。

   下面的代码为请求resnet50元信息的代码：

   ```python
   if __name__ == '__main__':
       test = AIServingWithGrpc(url="your ip", port="your port", model_name="resnet50")
       print(test._get_model_metadata())
   ```

   返回报错信息：

   ```
   Traceback (most recent call last):
     File "/tmp/pycharm_project_82/core/grpcclient.py", line 105, in <module>
       print(test._get_model_metadata())
     File "/tmp/pycharm_project_82/core/grpcclient.py", line 33, in _get_model_metadata
       response = stub.GetModelMetadata(self._model_spec())
     File "/root/anaconda3/envs/art/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
       return _end_unary_response_blocking(state, call, False, None)
     File "/root/anaconda3/envs/art/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
       raise _InactiveRpcError(state)
   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
   	status = StatusCode.UNKNOWN
   	details = ""
   	debug_error_string = "{"created":"@1627366617.381327534","description":"Error received from peer ipv4:xx.xx.xxx.x:xxxxx","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"","grpc_status":2}"
   ```

   调用Predict的gRPC接口同样会报错。

请帮忙查看是否是grpc的服务端出现的bug，谢谢。

**Comment by kingnop** [comment]
@aipredict 您好，不好意思，这边刚刚发现是我们客户端的请求没有按照要求写导致的bug，抱歉浪费您的时间。
